### ISSUE TITLE
Can not switch to english if another language is set by default

### ISSUE THREAD

**Issue by florianley** [hugo-toha/toha#916] opened 2024-03-31 13:05 UTC
## Expected Behavior
My default language is french set with DefaultContentLanguage: fr in my config.yaml. I would like to be able to switch to english

## Current Behavior
When I want to go from any language to english, I'm redirected to French

## Steps to Reproduce

here is the configuration of my config.yaml for langage section :
languages:
  fr:
    languageName: Francais
    disabled: false
    weight: 4
  de:
    languageName: Deutsch
    disabled: false
    weight: 2
  us:
    languageName: English
    disabled: false
    weight: 2
  en:
    languageName: English
    disabled: false
    weight: 0

DefaultContentLanguage: fr
defaultContentLanguageInSubdir: true

-> Open your website, try to switch to english. You are redirected to your default language

### Screenshots
<img width="1371" alt="image" src="https://github.com/hugo-toha/toha/assets/12626136/6f2c203d-2e99-4190-a1f2-35d8511d8324">

In this screenshot, href for english is href="/" but is correct for any other languages

### Browsers Affected

- [ x] Chrome
- [ x] Firefox
- [ x] Edge
- [ x] Safari 11
- [ x] Safari 10
- [ x] IE 11

**Comment by tht** [comment] 2024-04-30 08:44
Same issue here when trying to set German (de) as default.

**Comment by hossainemruz** [comment] 2024-05-10 18:16
I can confirm the issue.

**Comment by hossainemruz** [comment] 2024-05-10 19:59
The issue should be fixed now. Please, try pulling the latest change. Specify `defaultContentLanguage` to your default language.

**Closed** 2024-05-10 19:59 UTC
Labels: bug

**Comment by tht** [comment] 2024-05-11 17:38
Works for me, thanks a lot for looking into it and also for this lovely theme.
