### ISSUE TITLE
Problem with the background ?

### ISSUE THREAD

**Issue by t-benedet** [hugo-toha/toha#410] opened 2021-08-29 19:07 UTC
### Question

Hi,

I've closed my first issue and I open this one with more details :

I've a problem with the toha theme, when I try to change the background.

My config.toml : 
```
baseURL = 'https://ezzmazz.gitlab.io/blog/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'toha'

[params]
gitRepo = "https://gitlab.com/Ezzmazz/toha.git"
background = "images/default-background.jpg"
enableBlogPost = true
enableTOC = true

[params.logo]
main = "images/main-logo.png"
inverted = "images/inverted-logo.png"
favicon = "images/favicon.png"

[params.newsletter]
enable = true

```

As you can see, I've a put the paramater `background = "images/default-background.jpg"` but the picture doesn't appear as a background.

What I don't understand is : for the parameters `main`, `inverted` and `favicon`, each pictures are displayed correctly so why the parameters `background` doesn't works ?

I don't really understand where is the problem...

And I've noted an other problem ( don't know if this is the answer at my problem ). When I look the source code of my blog : 
<a href="https://zupimages.net/viewer.php?id=21/34/ctlw.png"><img src="https://zupimages.net/up/21/34/ctlw.png" alt="" /></a>

I can see that the URL of the picture is : `https://ezzmazz.gitlab.io/blog/blog/images/default-background.jpg`

Why there is two `blog` in the URL ? If I delete one of them, the pictures appears correctly...

There is some one to help me ? 

Thanks a lot ! 

My fork of the theme => [Ezzmazz toha theme fork](https://gitlab.com/Ezzmazz/toha)
My blog repo => https://ezzmazz.gitlab.io/blog/

**Comment by hossainemruz** [comment] 2021-08-30 03:53
The problem is happening because your `https://ezzmazz.gitlab.io/blog/`  has `blog` at the end. When the theme is trying to get the relative resource URL, its getting resource relative to `https://ezzmazz.gitlab.io` not relative to `https://ezzmazz.gitlab.io/blog/`. That's why this line is adding an extra `blog` at the resource url.
https://github.com/hugo-toha/toha/blob/c68a0e20afa24528ceeef85d2c3335fa0c76e9cd/layouts/partials/sections/home.html#L101

**Comment by t-benedet** [comment] 2021-08-30 18:56
Thanks for the answer.

So I've to update the BaseURL value in my config file ? 
```
baseURL = 'https://ezzmazz.gitlab.io'
```

If I do that, the theme doesn't appear as you can see here https://ezzmazz.gitlab.io/blog/

**Comment by t-benedet** [comment] 2021-08-31 12:31
Maybe the problem is that with gitlab, there is no `/blog` at the end of the github pages URL.

To use with gitlab, I've a found this workaround :

- Update the **home.html** file like that : 
```
<style>
    /* 0 to 299 */
    #homePageBackgroundImageDivStyled {
      /*background-image: url('{{ $tiny.RelPermalink }}'); This does not work on https://themes.gohugo.io/ */
      background-image: url('{{ strings.TrimSuffix "/" site.BaseURL }}/{{ $tiny }}');
    }
    /* 300 to X */
    @media (min-width: 500px) and (max-width: 800px) { /* or 301 if you want really the same as previously.  */
      #homePageBackgroundImageDivStyled {   
          background-image: url('{{ strings.TrimSuffix "/" site.BaseURL }}/{{ $small }}');
        }
    }
    @media (min-width: 801px) and (max-width: 1200px) { /* or 301 if you want really the same as previously.  */
      #homePageBackgroundImageDivStyled {   
          background-image: url('{{ strings.TrimSuffix "/" site.BaseURL }}/{{ $medium }}');
        }
    }
    @media (min-width: 1201px) and (max-width: 1500px) { /* or 301 if you want really the same as previously.  */
      #homePageBackgroundImageDivStyled {   
          background-image: url('{{ strings.TrimSuffix "/" site.BaseURL }}/{{ $large }}');
        }
    }
    @media (min-width: 1501px) { /* or 301 if you want really the same as previously.  */
      #homePageBackgroundImageDivStyled {   
          background-image: url('{{ strings.TrimSuffix "/" site.BaseURL }}/{{ $src }}');
        }
    }
    </style>

```

- Create an **images** directory in the static directory of the blog with de default-background.jpg inside, as you can see [here](https://gitlab.com/Ezzmazz/blog/-/tree/master/static/images)

- Keep the `/blog` at the end of the baseURL in the config.toml file : 
```
baseURL = 'https://ezzmazz.gitlab.io/blog
```

And it works.

I don't know if it could be useful for you.

**Comment by hossainemruz** [comment] 2021-08-31 12:48
Ok.  Then, I think you can close this issue.

**Closed** 2021-08-31 12:51 UTC
