### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Chow-Ray** [hugo-toha/toha#453] opened 2021-10-29 18:16 UTC
### Describe the solution you'd like
Can the navigation bar be displayed on pages such as post and notes?
![QQ截图20211030020945](https://user-images.githubusercontent.com/29678677/139483132-ae616ca7-3d87-4f05-b5ae-96fee1887ece.png)
![QQ截图20211030021145](https://user-images.githubusercontent.com/29678677/139483149-0e9a3f98-3bc2-4d46-bfc9-3dde5b4bd79b.png)

**Comment by hossainemruz** [comment] 2021-10-29 18:36
Duplicate of https://github.com/hugo-toha/toha/issues/435

**Closed** 2021-10-29 20:11 UTC
